######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 30 09:17:14 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h mThread.h mysym.h mytext.h
SOURCES += main.cpp mainwindow.cpp mThread.cpp mysym.cpp mytext.cpp
RESOURCES += dispDemo.qrc
